### ISSUE TITLE
machine should be the same for all instances from useMachine

### ISSUE THREAD

**Issue by TheAlemazing** [matthewp/robot-hooks#14]
const theGoodMachine = createMachine({foo: state(), bar: state()})
const [state, send] = useMachine(theGoodMachine)
const [state2, send2] = useMachine(theGoodMachine)

console.log(state === state2) // false
console.log(send === send2) // false

Expect:
console.log(state === state2) // true
console.log(send === send2) // true

**Comment by matthewp** [comment]
Why would you expect them to be the same? What's the use case? 

A machine is a little like a JavaScript constructor (or class) and calling useMachine is like creating an instance of that constructor.

**Comment by TheAlemazing** [comment]
I tried to use same machine for >2 components. 

App ( useMachine here )
- View 
- Edit

View & Edit both have the button that fire event 'toggle' to switch App state back and forth.
Now, I need to put 'send' as props of View and Edit component to use it later.

Is there another way?

Thank you.

**Comment by matthewp** [comment]
Yeah, passing `send` to child props seems reasonable to me. or pass them regular callbacks and call send yourself. Usually a machine is contained in a single component.
