### ISSUE TITLE
useMemo issue

### ISSUE THREAD

**Issue by hnordt** [matthewp/robot-hooks#4]
Here you are using a `useMemo` hook:

https://github.com/matthewp/robot-hooks/blob/master/machine.js#L17

I recommend using `useRef`.

Per React Hooks FAQ:

> **You may rely on useMemo as a performance optimization, not as a semantic guarantee.** In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components. Write your code so that it still works without useMemo — and then add it to optimize performance. (For rare cases when a value must never be recomputed, you can lazily initialize a ref.)
> https://reactjs.org/docs/hooks-faq.html#how-to-memoize-calculations

**Comment by matthewp** [comment]
Thanks! Can probably replace with useState(fn). I need to fix an unrelated bug and will do that then.

**Comment by matthewp** [comment]
Fixed in #5 (not yet released in react-robot though)
