### ISSUE TITLE
Passing an event to the context function

### ISSUE THREAD

**Issue by tschaub** [matthewp/robot-hooks#8]
I'm feeling like it would be useful for my component's props to be part of my machine context without triggering a change in state.  I could do this by having a factory function for a machine that accepted props and then made those available to the context.  Maybe something like this:

```js
function context(event) {
  return {
    // some context with data from event
  };
}

function contextWithProps(props) {
  return function(event) {
    return context(props);
  }
}

function createMachineWithProps(states, props) {
  return createMachine(states, contextWithProps(props));
}

function MyComponent(props) {
  const [current, send] = useMachine(createMachineWithProps(states, props));
  
  // etc
} 
```

But then I think I'd want to memoize those functions to return the same machine for the same props.

It feels like it would be more convenient to be able to pass a second "event" argument to `useMachine` that would get passed along as the third arg to `interpret` – so it would make it to my context creator.  So I'd do something like this instead:
```js
function context(event) {
  return {
    // some context with data from event
  };
}

const machine = createMachine(states, context);

function MyComponent(props) {
  const [current, send] = useMachine(machine, props);
  
  // etc
}
```

Maybe this is a Bad Idea.  But it also seems like it could be useful.  I'm curious if there are other recommended ways of initializing a context with props from a component.

**Comment by matthewp** [comment]
`interpret` can take a 3rd argument which is data passed to the context function. This just isn't wired up in robot-hooks yet.  When I add a test for your PR I'll try to add this in as well. Thanks for the suggestion!
